### ISSUE TITLE
Create Add Dish Form (Detailed) Component Mockup

### ISSUE THREAD

**Issue by timothyhuo1** [TaDish-App/TaDish#10]
Please complete work for this task in branch issue-10.

![Image](https://github.com/TaDish-App/TaDish/assets/61216890/c477a33f-394c-4f26-b3f0-f9ad9434bda9)

Under Home Page Flow 2. Create Add Dish Form (Detailed) Component. The middle 'Add' button should trigger a camera.

**Comment by alyssia-chen** [comment]
https://blog.logrocket.com/flutter-slider-widgets-deep-dive-with-examples/

**Comment by alyssia-chen** [comment]
Only added taste details (aka no sizes and "would eat again")
