### ISSUE TITLE
Create Favorite Component Page

### ISSUE THREAD

**Issue by timothyhuo1** [TaDish-App/TaDish#19]
Please complete work for this task in branch issue-19.

![Image](https://github.com/TaDish-App/TaDish/assets/61216890/f20ac947-3060-439f-8479-6d8d31aedfa3)
![Image](https://github.com/TaDish-App/TaDish/assets/61216890/e6b29fca-d6c0-43b6-8352-14ca0336ec98)

Under Profile Page. Create a Favorite Component Page to review dishes you favorited.

**Comment by alyssia-chen** [comment]
Sorry accidentally created it under profile component brand #8
