### ISSUE TITLE
Create Saved Page Mockup

### ISSUE THREAD

**Issue by timothyhuo1** [TaDish-App/TaDish#4]
Please complete work for this task in branch issue-4.

![Image](https://github.com/TaDish-App/TaDish/assets/61216890/b619e132-a13f-4a7b-b508-73814d773c76)

Create a Saved Page Mockup to display all the saved dishes you haven't tried yet.

**Comment by alyssia-chen** [comment]
omitted heart from diagram because all with hearted since all saved (drawing is in the past for a feed). Also removed time/date because it's not necessary
