### ISSUE TITLE
Create Home Page Mockup

### ISSUE THREAD

**Issue by timothyhuo1** [TaDish-App/TaDish#5]
Please complete work for this task in branch issue-5.

![Image](https://github.com/TaDish-App/TaDish/assets/61216890/4790bf3a-3734-4cc1-ad3b-5c2f2c8020f0)

Create a Home Page Mockup showing dishes or straight to posting a dish review.

**Comment by alyssia-chen** [comment]
- [ ] Main Header
- [ ] Secondary header
- [ ] Image upload
- [ ] Star rating
- [ ] Tags
- [ ] Public note (open up as modal)
- [ ] Private note (open up as modal)
- [ ] move on to next page button

- Column
  - Row
    - Left text
    - Left Text
  - Row
    - Centered image upload component
  - Row
    - Centered star component (https://github.com/sarbagyastha/flutter_rating_bar)
  - Row
    - https://m2.material.io/components/chips/flutter#using-chips
  - Row
    - Column
      - Stack
        - Background (unless can change background of input text)
        - Input text area
    - Column
      - Stack
        - Background (unless can change background of input text)
        - Input text area
  - Row
    - Right justified submit button
