### ISSUE TITLE
Create Profile Page Mockup

### ISSUE THREAD

**Issue by timothyhuo1** [TaDish-App/TaDish#8]
Please complete work for this task in branch issue-8.

![Image](https://github.com/TaDish-App/TaDish/assets/61216890/74bdaa7f-0c44-4ba7-8660-4b7a6b927dfc)

Create a Profile Page Mockup showing your personal information, taste preferences, and past history of foods you tried.

**Comment by alyssia-chen** [comment]
Profile inspo
![Image](https://github.com/TaDish-App/TaDish/assets/84742988/2d8ed4f1-6639-4a2e-a333-f18b51fd79ed)
![Image](https://github.com/TaDish-App/TaDish/assets/84742988/423ef93c-68eb-4c94-b1a3-b74075d804d9)

**Comment by alyssia-chen** [comment]
- [ ] Column
  - [ ] Profile pic (radar graph)
  - [ ] Full name
  - [ ] Row
    - [ ] icon + @username
    - [ ] icon + Location
  - [ ] Row
    - [ ] Button = Favorites lit up
    - [ ] Button = History
  - [ ] Row
    - [ ] Num Dishes rated
    - [ ] Num friends
    - [ ] Num vegan/local/vegetarian
  - [ ] Switch between the two based on button
    - [ ] Favorites as Pinterest style
    - [ ] History of places visited
